name: CampusTown
main: me.jackgoldsworth.campustown.CampusTown
author: Jack Goldsworth
description: Custom plugin for the campus town bois.
version: 1.0.0
api-version: "1.15"

commands:
  fakejob:
    description: Tell Joe that his job is fake.
    usage: /<command>
  d20:
    description: Roll a dice 20.
    usage: /<command>
  setprefix:
    description: Set a prefix on your username.
    usage: /<command> <prefix>
  sethome:
    description: Set a players home.
    usage: /<command>
  home:
    description: Teleports the player home.
    usage: /<command>
  shop:
    description: Opens a shop to spend points.
    usage: /<command>
  stats:
    description: Let's a user see their current stats.
    usage: /<command>